language: go

go:
  - tip

before_install:
  - go get -tags=debug -t -v ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)